apiVersion: v1
kind: ConfigMap
metadata:
  name: vfio-device-plugin-config
  namespace: kube-system
data:
  config.yml: |
    - resourceName: ascend/910b
      vendorId: '19e5'
      deviceId: ['d802']
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vfio-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: vfio-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: vfio-device-plugin
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: vfio-device-plugin
        image: dreg.cloud.sdu.dk/infrastructure/vfio-device-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugins
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: config
            mountPath: /root/config
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: config
          configMap:
            name: vfio-device-plugin-config
